// Define the type for a single property listing
export type Listing = {
  AssociateId: number;
  AssociationNotes: string | null;
  BathroomsFull: number | null;
  BedroomsTotal: number | null;
  ConstructionSize: number;
  ConstructionSizeLiving: number;
  ConstructionSizeTotal: number | null;
  ConstructionSizeUnits: string;
  ContractType_en: string;
  ContractType_es: string;
  Cooling: string;
  Country: string;
  CountryId: number;
  CurrencyId: number;
  CurrencyListPrice: string;
  EmbeddedVideoCode: string | null;
  ExpirationDate: string;
  FirstName: string;
  Furnishedyn: string;
  Garage: string;
  GarageCovered: string;
  GarageOpen: string;
  GarageSpaces: number;
  GatedCommunity: string;
  Images: string; // Pipe-separated string of image URLs
  LastName: string;
  Latitude: string;
  ListPrice: number;
  ListingContractDate: string;
  ListingContractType: number;
  ListingId: string;
  ListingKey: string;
  ListingProbableuseId: number;
  ListingTitle_en: string;
  ListingTitle_es: string;
  Listingagreementyn: string;
  Location: string;
  LocationId: number;
  Longitude: string;
  LotSizeArea: number;
  LotSizeUnits: string;
  LotSizeUnitsId: number;
  MaidRoom: string;
  OfficeID: number;
  OfficeName: string;
  PoolPrivate: string;
  ProbableUse: string;
  PropertyTypeName_en: string;
  PropertyTypeName_es: string;
  PublicRemarks_en: string;
  StateDepProv: string;
  StateDepProvId: number;
  Status: string;
  Stories: number | null;
  UnparsedAddress: string;
  Videolink: string | null;
  Viewyn: string;
  publicRemarks_es: string;
};

export type PropertiesResponse = {
  data: Listing[];
  totalPages: number;
  currentPage: number;
};
